# fly.toml app configuration file generated for openvibe on 2025-09-13T00:33:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# This app now serves both React frontend (via nginx) and Python backend (via Flask)
# - Frontend: served at / (React SPA)
# - Backend API: served at /api/* (proxied to Python Flask app)

app = 'openvibe'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 4096

[experimental]
  enable_consul = false
  enable_etcd = false

[processes]
  app = "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

# Enable Docker-in-Docker capabilities
[deploy]
  strategy = "immediate"

[env]
  DOCKER_HOST = "unix:///var/run/docker.sock"
  AGENT_SERVER_IMAGE = "ghcr.io/all-hands-ai/agent-server:ea72d20@sha256:39c72c4796bb30f8d08d4cefbe3aa48b49f96c26eae6e7d79c4a8190fd10865f"

[mounts]
  source = "data_volume"
  destination = "/data"
