name: Backend Tests

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  backend-tests:
    name: Backend Tests (Pytest)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Create virtual environment
        run: uv venv
        working-directory: backend

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[dev]"
        working-directory: backend

      - name: Create test data directory
        run: mkdir -p /tmp/test-data
        
      - name: Run pytest with coverage
        run: |
          source .venv/bin/activate
          pytest --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing -v
        working-directory: backend
        env:
          DATA_DIR: /tmp/test-data

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: backend/
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/htmlcov/
          retention-days: 7

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/coverage.xml
          retention-days: 7

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_PATH: backend/coverage.xml

      - name: Generate test summary
        if: always()
        run: |
          echo "## Backend Test Results" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Pytest tests completed" >> $GITHUB_STEP_SUMMARY
          echo "- 📊 Coverage report generated" >> $GITHUB_STEP_SUMMARY
          if [ -f "backend/coverage.xml" ]; then
            echo "- 📈 Coverage details available in artifacts" >> $GITHUB_STEP_SUMMARY
          fi